language: node_js

services:
    - postgresql

before_script:
    -psql -c 'create database test;' -U postgres
    -node server/models/db.js
    -node serer/helper/populatedb.js

script:
    -mocha unittests.js --exit

install:
    -npm install 
