language: node_js
node_js:
    - "node"
services:
    - postgresql
before_script:
    - psql -c 'create database test;' -U postgres
    - node server/models/db.js
    - node server/helper/populatedb.js